language: java

jdk:
  - oraclejdk8

before_deploy:
  - mvn help:evaluate -N -Dexpression=project.version | grep -v '\['
  - export project_version=$(mvn help:evaluate -N -Dexpression=project.version | grep -v '\[')

install:
  # Override default travis to use the maven wrapper
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=false -B -V

deploy:
  provider: releases
  api_key:
    secure: fxaxuRfBDFtEdphVUg3sXHnd0C8hUQH3FmMZy3unD3f91IT57wvUzf/CI1aylfR+WKiF+XyFWdj2ho7EuI+SapTRk8asY0KNjE3b1DzK1TimjPSHbecXs2tYt1hW12ryXds7RsxFtdfXMOqNl4hevN95jZFD2Nr7Z9XAONneNbWQjeWdJpDP0FluFZ2ppMk0+aNvRC/3gbyLtlGnOkCoMRDxkgneUh73YPSphvYEX+4FQ05mHA4aNi6tWUG201kcqy4a/2dChgjqVIH0ooPn84vu7LcSkPrnN2U4HYtmqRTQjX7ElBOgBBnCEhFnajRFk8/unntNIr588/YHrdzFhq68+V32zrYP+OrefyE3r77ZLEtthOn6g5+Y0+a/Uozz1aNReV3mzvSBO5X88rxZWnk2klu80X/CXllCoRezR/u/VhTh0fS2k1qriDyenCoh3ByUCoP7XNNZrJPaB4v06G3qph8kkeXYeOlvx1RK2sB0Gic6yRjtuvqyMKPDow/RoBPF5TGXph1V/CDN0IZKVzvFBTTphFpfT+0WeIIKVQdCqX1bD3uzH7OAfMy1mSia36of67xEvmJ/abrDiUKcEm8F3mq/Eh06Jc5lv5ip91UvzwrbX8CxJIBU/flHXtTzIexMqMLj3TWCNtNQe4TUMdmTOBAHAMI7Jr9wRPfW/JM=
  file:
    - "target/popout-$project_version.jar"
    - "target/popout-$project_version-javadoc.jar"
    - "target/popout-$project_version-sources.jar"
  skip_cleanup: true
  on:
    repo: infobip/popout
  name: $project_version
