
language: java

jdk:
  - openjdk8

install:
  mvn --settings .settings.xml install -DskipTests=true -Dmaven.javadoc.skip=true -Dgpg.skip -B -V

script:
  mvn --settings .settings.xml clean verify -DskipTests=false -Dmaven.javadoc.skip=true -Dgpg.skip -B -U

before_deploy:
  - mvn help:evaluate -N -Dexpression=project.version | grep -v '\['
  - export project_version=$(mvn help:evaluate -N -Dexpression=project.version | grep -v '\[')
  - echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import
  - echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust
  - sed -i -- "s/\${env.SONATYPE_PASSWORD}/$SONATYPE_PASSWORD/g" .settings.xml
  - mvn --settings .settings.xml clean deploy -DskipTests=true -Dmaven.javadoc.skip=false -B -U

deploy:
  provider: releases
  api_key:
    secure: qm0m1p6B7VgvJpGcEpZnBZi3iRP3VHUvm5T0NmUlFzpA9O65Wlzmbz2JL7Li6xibv885e3rwYoKYx80kiWFqHNle2xfBNX2WlCiP0fFHRMm3KNkhR5SLDrCHZNomKqFLd/OjRL1pPRaHkjQtvaseU/Muf5kgBcMg+5+VgzekS1nN6hcxk0lIo+MMAzYa7QNpE4geiA01hcl2ngyIemGGxiX0p3xOsgemSHdXVv2cjz51IMImV07yucvccoswY+esYZNASg/Da4Oi7blCUn1kKXUE9ihOIrVrltxGow6aBOEo6nHiELG4zAOtoLTHOWycxiakP+7OryOhLOeQ1YruJt4WPJ9dq0Erh7WNn5O2y8beWTLXqyXK9wd/YTM6ax93sHaG2JbirqlXcgVfYAKZrhb45FndRIsWvyme/RCTzvFpNw4ts5FPy3mzbLU01X48EN1ThkxmVWsG+2TVVf7d/BR22U6+Vh2jZbOZzYl4eqVCExEk3bS06tg57bid93t0jHE1pnBOv256zXdMkt5EoEG7c0GjgI3isLwvMvJHAIIzloRW744Q48jNUsVh4mD7r/yD3RmFmPFb67UrbuBdP2Ia4aJT2/ZrVY9GJtTAXvpZ5EkjKmujsap5bTjsAX2M2kvbQ0g1+mYfUc07/DLsuEeS6EY5/XgzaTNU4SK6A+E=
  file:
    - "popout/target/popout-$project_version.jar"
    - "popout/target/popout-$project_version-javadoc.jar"
    - "popout/target/popout-$project_version-sources.jar"
  skip_cleanup: true
  on:
    tags: true
    repo: infobip/popout
  name: $project_version
